language: node_js

node_js:
  - node

cache:
  directories:
    - node_modules

before_script:
  - yarn global add codecov

script:
  - yarn test --coverage
  - codecov --token=$CODECOV_TOKEN

deploy:
  - provider: pages
    local-dir: docs/.vuepress/dist
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: npm
    email: laomao800@gmail.com
    api_key: $NPM_TOKEN
    on:
      tags: true
